@tool
extends RefCounted
class_name DeliberateRelicCatalog
## Registry of deliberate pinball relics (TASK-093 / TASK-094).
## 7 Core Archetypes x 3 Tiers x 2 Variations = 42 Deliberate Relics.

const PolyominoModuleData = preload("res://resources/polyomino/polyomino_module_data.gd")

const CellType = PolyominoModuleData.CellType
const GoalArchetype = PolyominoModuleData.GoalArchetype
const RewardType = PolyominoModuleData.RewardType
const EnclosureType = PolyominoModuleData.EnclosureType
const MachineryLayoutMode = PolyominoModuleData.MachineryLayoutMode

static var _CATALOG: Dictionary = {}
static var _GOALS: Dictionary = {}

static func get_catalog() -> Dictionary:
	if not _CATALOG.is_empty():
		return _CATALOG
	_build_catalog()
	return _CATALOG

static func get_goals() -> Dictionary:
	if not _GOALS.is_empty():
		return _GOALS
	_build_catalog()
	return _GOALS

static func has_relic(id: StringName) -> bool:
	return get_catalog().has(id)

static func get_relic(id: StringName) -> Dictionary:
	return get_catalog().get(id, {})

static func get_goal(id: StringName) -> Dictionary:
	return get_goals().get(id, {})

static func get_all_ids() -> Array[StringName]:
	var ids: Array[StringName] = []
	for k in get_catalog():
		ids.append(k)
	return ids

static func _def(id: StringName, name: String, tier: int, shape: String, m_desc: String, cells: Array[Vector2i], types: Dictionary = {}, dirs: Dictionary = {}, enclosure: int = EnclosureType.OPEN_FRAME, letters: Dictionary = {}, layout_mode: int = MachineryLayoutMode.PER_CELL, unified_type: int = CellType.EMPTY, goal: Dictionary = {}) -> void:
	_CATALOG[id] = {
		"display_name": name, "tier": tier, "shape_name": shape, "machinery_desc": m_desc,
		"cells": cells, "cell_types": types, "cell_directions": dirs, "energy_values": {},
		"cell_letters": letters, "bumper_durability": 0, "enclosure_type": enclosure,
		"custom_wall_edges": {}, "layout_mode": layout_mode, "unified_component_type": unified_type
	}
	if not goal.is_empty():
		_GOALS[id] = goal

static func _build_catalog() -> void:
	_CATALOG.clear()
	_GOALS.clear()
	_build_bumper_vessels()
	_build_word_banks()
	_build_wire_reservoirs()
	_build_detonation_triangles()
	_build_bash_toys()
	_build_spinners()
	_build_momentum_tracks()

static func _build_bumper_vessels() -> void:
	# T1
	_def(&"bumper_vessel_twin", "Twin Core Bumper Vessel", 1, "2x3 Vertical Chamber", "2 Pop Bumpers in open vertical chute. Ricochets balls to generate rapid bounce energy.", [Vector2i(0,0), Vector2i(1,0), Vector2i(0,1), Vector2i(1,1), Vector2i(0,2), Vector2i(1,2)], {Vector2i(0,1): CellType.POP_BUMPER, Vector2i(1,1): CellType.POP_BUMPER}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SUPER_JETS, "reward": RewardType.ENERGY_SURGE, "title": "Twin Bounce Surge", "desc": "Bounce between twin bumpers.", "activation_req": "Hit twin bumpers 4 times.", "reward_desc": "+30 Energy Surge to ball", "energy": 30, "required_widget": CellType.POP_BUMPER, "threshold": 4})
	_def(&"bumper_vessel_stagger", "Staggered Bumper Chute", 1, "3x2 Chevron Funnel", "3 Staggered Bumpers in open funnel. Deflects descending balls into rapid side-bounces.", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(0,1), Vector2i(1,1), Vector2i(2,1)], {Vector2i(0,0): CellType.BUMPER, Vector2i(1,1): CellType.BUMPER, Vector2i(2,0): CellType.BUMPER}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SUPER_JETS, "reward": RewardType.ENERGY_SURGE, "title": "Staggered Deflection", "desc": "Bounce across staggered bumpers.", "activation_req": "Hit staggered bumpers 5 times.", "reward_desc": "+35 Energy Surge to ball", "energy": 35, "required_widget": CellType.BUMPER, "threshold": 5})
	# T2
	_def(&"pachinko_bumper_vessel", "Pachinko Bumper Vessel", 2, "3x3 Round Chamber", "4 Pop Bumpers in open spherical frame. High-frequency bounce energy before bottom exit.", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(0,1), Vector2i(2,1), Vector2i(0,2), Vector2i(1,2), Vector2i(2,2)], {Vector2i(1,0): CellType.POP_BUMPER, Vector2i(0,1): CellType.POP_BUMPER, Vector2i(2,1): CellType.POP_BUMPER, Vector2i(1,2): CellType.POP_BUMPER}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SUPER_JETS, "reward": RewardType.ENERGY_SURGE, "title": "Pachinko Cascade", "desc": "Bounce through bumper core.", "activation_req": "Hit bumper core 8 times.", "reward_desc": "+60 Energy Surge to ball", "energy": 60, "required_widget": CellType.POP_BUMPER, "threshold": 8})
	_def(&"bumper_vessel_pinball", "Pinball Bounce Chamber", 2, "3x3 Octagon Chamber", "3 Pop Bumpers + 1 Center Bumper in octagonal frame. Heavy kinetic ricochets.", [Vector2i(1,0), Vector2i(0,1), Vector2i(1,1), Vector2i(2,1), Vector2i(0,2), Vector2i(1,2), Vector2i(2,2)], {Vector2i(0,1): CellType.POP_BUMPER, Vector2i(2,1): CellType.POP_BUMPER, Vector2i(1,1): CellType.BUMPER, Vector2i(1,2): CellType.POP_BUMPER}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SUPER_JETS, "reward": RewardType.ENERGY_SURGE, "title": "Octagon Ricochet", "desc": "Ricochet off octagon bumpers.", "activation_req": "Hit octagon bumpers 8 times.", "reward_desc": "+70 Energy Surge to ball", "energy": 70, "required_widget": CellType.POP_BUMPER, "threshold": 8})
	# T3
	_def(&"mega_pop_bumper", "Mega Bumper Citadel", 3, "2x2 Square Block", "Unified 4-Peg Mega Bumper Core (+20 Energy, 650 Impulse). Giant setpiece core that repels balls violently.", [Vector2i(0,0), Vector2i(1,0), Vector2i(0,1), Vector2i(1,1)], {}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.UNIFIED, CellType.POP_BUMPER, {"type": GoalArchetype.SUPER_JETS, "reward": RewardType.ENERGY_SURGE, "title": "Mega Bumper Overcharge", "desc": "Hit mega pop bumper 5 times.", "activation_req": "Hit mega pop bumper 5 times.", "reward_desc": "+120 Energy Surge to ball", "energy": 120, "required_widget": CellType.POP_BUMPER, "threshold": 5})
	_def(&"cyclone_bounce_vault", "Cyclone Bounce Vault", 3, "4x3 Horseshoe Chamber", "5 Dense Pop Bumpers in curved vault. Extreme bounce density and massive kinetic surge.", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(3,0), Vector2i(0,1), Vector2i(3,1), Vector2i(0,2), Vector2i(1,2), Vector2i(2,2), Vector2i(3,2)], {Vector2i(0,0): CellType.POP_BUMPER, Vector2i(3,0): CellType.POP_BUMPER, Vector2i(1,1): CellType.POP_BUMPER, Vector2i(2,1): CellType.POP_BUMPER, Vector2i(1,2): CellType.POP_BUMPER}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SUPER_JETS, "reward": RewardType.ENERGY_SURGE, "title": "Cyclone Vault Surge", "desc": "Bounce through cyclone vault.", "activation_req": "Hit vault bumpers 10 times.", "reward_desc": "+150 Energy Surge to ball", "energy": 150, "required_widget": CellType.POP_BUMPER, "threshold": 10})

static func _build_word_banks() -> void:
	# T1
	_def(&"word_bank_gob", "G-O-B Word Bank", 1, "3x2 Horizontal Bar", "3 Rollover Switches (G-O-B) in divided lanes. Lighting unlit switch grants bonus ball energy; spelling word triggers bank bonus and resets.", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(0,1), Vector2i(1,1), Vector2i(2,1)], {Vector2i(0,0): CellType.ROLLOVER_SWITCH, Vector2i(1,0): CellType.ROLLOVER_SWITCH, Vector2i(2,0): CellType.ROLLOVER_SWITCH}, {}, EnclosureType.DIVIDED_LANES, {Vector2i(0,0): "G", Vector2i(1,0): "O", Vector2i(2,0): "B"}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.ROLLOVER_SPELL, "reward": RewardType.ENERGY_SURGE, "title": "G-O-B Bank Clear", "desc": "Spell G-O-B across lanes.", "activation_req": "Spell G-O-B across lanes.", "reward_desc": "+40 Energy Surge to ball", "energy": 40, "required_widget": CellType.ROLLOVER_SWITCH, "threshold": 3})
	_def(&"word_bank_pop", "P-O-P Word Bank", 1, "3x2 Stepped Chute", "3 Rollover Switches (P-O-P) in divided lanes. Grants +10 energy per unlit switch; spelling word grants +45 energy and resets.", [Vector2i(0,0), Vector2i(1,0), Vector2i(1,1), Vector2i(2,1), Vector2i(0,1)], {Vector2i(0,0): CellType.ROLLOVER_SWITCH, Vector2i(1,1): CellType.ROLLOVER_SWITCH, Vector2i(2,1): CellType.ROLLOVER_SWITCH}, {}, EnclosureType.DIVIDED_LANES, {Vector2i(0,0): "P", Vector2i(1,1): "O", Vector2i(2,1): "P"}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.ROLLOVER_SPELL, "reward": RewardType.ENERGY_SURGE, "title": "P-O-P Bank Clear", "desc": "Spell P-O-P across lanes.", "activation_req": "Spell P-O-P across lanes.", "reward_desc": "+45 Energy Surge to ball", "energy": 45, "required_widget": CellType.ROLLOVER_SWITCH, "threshold": 3})
	# T2
	_def(&"word_bank_win", "W-I-N Word Bank", 2, "3x3 V-Chamber", "3 Rollover Switches (W-I-N) with divided lanes and 2 pop bumpers. Grants +15 energy per unlit switch; spelling word grants +80 energy and resets.", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(1,1), Vector2i(0,2), Vector2i(2,2)], {Vector2i(0,0): CellType.ROLLOVER_SWITCH, Vector2i(1,0): CellType.ROLLOVER_SWITCH, Vector2i(2,0): CellType.ROLLOVER_SWITCH, Vector2i(0,2): CellType.POP_BUMPER, Vector2i(2,2): CellType.POP_BUMPER}, {}, EnclosureType.DIVIDED_LANES, {Vector2i(0,0): "W", Vector2i(1,0): "I", Vector2i(2,0): "N"}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.ROLLOVER_SPELL, "reward": RewardType.ENERGY_SURGE, "title": "W-I-N Bank Clear", "desc": "Spell W-I-N across lanes.", "activation_req": "Spell W-I-N across lanes.", "reward_desc": "+80 Energy Surge to ball", "energy": 80, "required_widget": CellType.ROLLOVER_SWITCH, "threshold": 3})
	_def(&"word_bank_bam", "B-A-M Word Bank", 2, "2x3 L-Chamber", "3 Rollover Switches (B-A-M) in divided vertical lanes + 1 rotary booster. Grants +15 energy per switch; spelling B-A-M triggers Global Board Knock and resets.", [Vector2i(0,0), Vector2i(1,0), Vector2i(0,1), Vector2i(0,2), Vector2i(1,2)], {Vector2i(0,0): CellType.ROLLOVER_SWITCH, Vector2i(0,1): CellType.ROLLOVER_SWITCH, Vector2i(0,2): CellType.ROLLOVER_SWITCH, Vector2i(1,0): CellType.ROTARY_BOOSTER}, {}, EnclosureType.DIVIDED_LANES, {Vector2i(0,0): "B", Vector2i(0,1): "A", Vector2i(0,2): "M"}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.ROLLOVER_SPELL, "reward": RewardType.GLOBAL_BOARD_KNOCK, "title": "B-A-M Word Bank", "desc": "Spell B-A-M across lanes.", "activation_req": "Spell B-A-M across lanes.", "reward_desc": "Global Board Knock (All pegs hit once)", "required_widget": CellType.ROLLOVER_SWITCH, "threshold": 3})
	# T3
	_def(&"word_bank_boom", "B-O-O-M Word Bank", 3, "4x3 Grand Bank", "4 Rollover Switches (B-O-O-M) in 4 divided vertical lanes. Grants +20 energy per unlit switch; spelling word triggers +150 Energy and Global Board Knock.", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(3,0), Vector2i(0,1), Vector2i(1,1), Vector2i(2,1), Vector2i(3,1), Vector2i(0,2), Vector2i(3,2)], {Vector2i(0,0): CellType.ROLLOVER_SWITCH, Vector2i(1,0): CellType.ROLLOVER_SWITCH, Vector2i(2,0): CellType.ROLLOVER_SWITCH, Vector2i(3,0): CellType.ROLLOVER_SWITCH}, {}, EnclosureType.DIVIDED_LANES, {Vector2i(0,0): "B", Vector2i(1,0): "O", Vector2i(2,0): "O", Vector2i(3,0): "M"}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.ROLLOVER_SPELL, "reward": RewardType.ENERGY_SURGE, "title": "B-O-O-M Bank Clear", "desc": "Spell B-O-O-M across lanes.", "activation_req": "Spell B-O-O-M across lanes.", "reward_desc": "+150 Energy Surge + Global Knock", "energy": 150, "required_widget": CellType.ROLLOVER_SWITCH, "threshold": 4})
	_def(&"word_bank_loot", "L-O-O-T Word Bank", 3, "4x3 Vault Bank", "4 Rollover Switches (L-O-O-T) in divided lanes with 2 corner bumpers. Spelling word unleashes a Multiball Cascade (3 balls) and resets.", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(3,0), Vector2i(0,1), Vector2i(3,1), Vector2i(0,2), Vector2i(1,2), Vector2i(2,2), Vector2i(3,2)], {Vector2i(0,0): CellType.ROLLOVER_SWITCH, Vector2i(1,0): CellType.ROLLOVER_SWITCH, Vector2i(2,0): CellType.ROLLOVER_SWITCH, Vector2i(3,0): CellType.ROLLOVER_SWITCH, Vector2i(0,2): CellType.POP_BUMPER, Vector2i(3,2): CellType.POP_BUMPER}, {}, EnclosureType.DIVIDED_LANES, {Vector2i(0,0): "L", Vector2i(1,0): "O", Vector2i(2,0): "O", Vector2i(3,0): "T"}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.ROLLOVER_SPELL, "reward": RewardType.MULTIBALL_CASCADE, "title": "L-O-O-T Bank Clear", "desc": "Spell L-O-O-T across lanes.", "activation_req": "Spell L-O-O-T across lanes.", "reward_desc": "Multiball Cascade (3 balls)", "balls": 3, "required_widget": CellType.ROLLOVER_SWITCH, "threshold": 4})

static func _build_wire_reservoirs() -> void:
	# T1
	_def(&"wire_gate_cup", "Retention Catch Cup", 1, "2x2 Catch Cup", "Wire Gate Retention Cup. Holds 2 falling balls, then opens to release them in a twin volley with +40 energy.", [Vector2i(0,0), Vector2i(1,0), Vector2i(0,1), Vector2i(1,1)], {Vector2i(0,1): CellType.WIRE_GATE}, {Vector2i(0,1): Vector2i.DOWN}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SINKHOLE_LOCK, "reward": RewardType.ENERGY_SURGE, "title": "Twin Cup Release", "desc": "Fill cup with 2 balls.", "activation_req": "Catch 2 balls in cup.", "reward_desc": "+40 Energy Surge to ball", "energy": 40, "required_widget": CellType.WIRE_GATE, "threshold": 2})
	_def(&"wire_gate_funnel", "Funnel Retention Chute", 1, "2x3 Funnel Basin", "Wire Gate Funnel Chute. Catches and retains 3 balls before opening with a +50 energy burst.", [Vector2i(0,0), Vector2i(1,0), Vector2i(0,1), Vector2i(1,1), Vector2i(0,2)], {Vector2i(0,2): CellType.WIRE_GATE}, {Vector2i(0,2): Vector2i.DOWN}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SINKHOLE_LOCK, "reward": RewardType.ENERGY_SURGE, "title": "Funnel Chute Release", "desc": "Fill funnel with 3 balls.", "activation_req": "Catch 3 balls in funnel.", "reward_desc": "+50 Energy Surge to ball", "energy": 50, "required_widget": CellType.WIRE_GATE, "threshold": 3})
	# T2
	_def(&"wire_gate_reservoir", "Wire Gate Retention Reservoir", 2, "3x3 Reservoir Basin", "Wire Gate Retention Basin. Holds up to 4 balls behind a closed gate, swinging open for a cascading release and +90 energy.", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(0,1), Vector2i(2,1), Vector2i(0,2), Vector2i(1,2), Vector2i(2,2)], {Vector2i(1,2): CellType.WIRE_GATE, Vector2i(0,1): CellType.BUMPER, Vector2i(2,1): CellType.BUMPER}, {Vector2i(1,2): Vector2i.DOWN}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SINKHOLE_LOCK, "reward": RewardType.ENERGY_SURGE, "title": "Reservoir Cascade", "desc": "Fill reservoir with 4 balls.", "activation_req": "Catch 4 balls in reservoir.", "reward_desc": "+90 Energy Surge to ball", "energy": 90, "required_widget": CellType.WIRE_GATE, "threshold": 4})
	_def(&"abyssal_maw", "Abyssal Holding Well", 2, "2x2 Square Well", "Unified 4-Peg Ball Trap. Captures falling balls in a deep retention well and erupts in a 3-ball ejection volley.", [Vector2i(0,0), Vector2i(1,0), Vector2i(0,1), Vector2i(1,1)], {}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.UNIFIED, CellType.BALL_TRAP, {"type": GoalArchetype.SINKHOLE_LOCK, "reward": RewardType.MULTIBALL_CASCADE, "title": "Abyssal Eruption", "desc": "Capture balls in abyssal maw.", "activation_req": "Catch 3 balls in abyssal maw.", "reward_desc": "Multiball Cascade (3 balls)", "balls": 3, "required_widget": CellType.BALL_TRAP, "threshold": 3})
	# T3
	_def(&"fragment_swarm", "Grand Wire Reservoir", 3, "3x4 Giant Arch", "Giant Arch Wire Gate Reservoir. Traps 3 balls before bursting open to release a massive cascading storm.", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(0,1), Vector2i(2,1), Vector2i(0,2), Vector2i(2,2), Vector2i(0,3), Vector2i(1,3), Vector2i(2,3), Vector2i(1,2)], {Vector2i(1,0): CellType.WIRE_GATE, Vector2i(0,3): CellType.BUMPER, Vector2i(2,3): CellType.BUMPER}, {Vector2i(1,0): Vector2i.DOWN}, EnclosureType.DIRECTIONAL_FUNNEL, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SINKHOLE_LOCK, "reward": RewardType.MULTIBALL_CASCADE, "title": "Grand Cascade Eruption", "desc": "Fill grand reservoir with 3 balls.", "activation_req": "Catch 3 balls in reservoir.", "reward_desc": "Multiball Cascade (4 balls)", "balls": 4, "required_widget": CellType.WIRE_GATE, "threshold": 3})
	_def(&"wire_gate_armory", "Armory Ball Vault", 3, "4x3 Fortress Reservoir", "Fortress Wire Gate Vault. Holds 5 balls behind heavy gate; opening triggers Global Board Knock and +130 Energy Surge.", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(3,0), Vector2i(0,1), Vector2i(3,1), Vector2i(0,2), Vector2i(1,2), Vector2i(2,2), Vector2i(3,2)], {Vector2i(1,2): CellType.WIRE_GATE, Vector2i(2,2): CellType.WIRE_GATE, Vector2i(0,1): CellType.POP_BUMPER, Vector2i(3,1): CellType.POP_BUMPER}, {Vector2i(1,2): Vector2i.DOWN, Vector2i(2,2): Vector2i.DOWN}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SINKHOLE_LOCK, "reward": RewardType.GLOBAL_BOARD_KNOCK, "title": "Armory Vault Breach", "desc": "Fill vault with 5 balls.", "activation_req": "Catch 5 balls in vault.", "reward_desc": "Global Board Knock + 130 Energy", "energy": 130, "required_widget": CellType.WIRE_GATE, "threshold": 5})

static func _build_detonation_triangles() -> void:
	# T1
	_def(&"detonation_triangle_wedge", "Crackling Wedge Kicker", 1, "3-Cell Corner L", "Hypotenuse Slingshot Kicker. Charges with electrical crackle on each hit (2 hits to detonate with +35 energy).", [Vector2i(0,0), Vector2i(1,0), Vector2i(0,1)], {Vector2i(0,0): CellType.SLINGSHOT}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.TACTICAL_REBOUND, "reward": RewardType.ENERGY_SURGE, "title": "Wedge Detonation", "desc": "Charge wedge slingshot.", "activation_req": "Deflect off wedge 2 times.", "reward_desc": "+35 Energy Surge to ball", "energy": 35, "required_widget": CellType.SLINGSHOT, "threshold": 2})
	_def(&"detonation_triangle_acute", "Acute Slingshot Triangle", 1, "3-Cell Diagonal Spike", "Angled Slingshot Wedge. Deflects balls with sharp impulse, building electric charge (3 hits to detonate with +40 energy).", [Vector2i(0,0), Vector2i(1,0), Vector2i(1,1)], {Vector2i(1,0): CellType.SLINGSHOT}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.TACTICAL_REBOUND, "reward": RewardType.ENERGY_SURGE, "title": "Acute Triangle Blast", "desc": "Charge acute slingshot.", "activation_req": "Deflect off triangle 3 times.", "reward_desc": "+40 Energy Surge to ball", "energy": 40, "required_widget": CellType.SLINGSHOT, "threshold": 3})
	# T2
	_def(&"corner_slingshot", "Crackling Detonation Triangle", 2, "3-Peg Corner L", "Unified Diagonal Corner Slingshot Kicker. Crackling electrical blue arcs intensify until detonating with +75 energy surge.", [Vector2i(0,0), Vector2i(1,0), Vector2i(0,1)], {}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.UNIFIED, CellType.SLINGSHOT, {"type": GoalArchetype.TACTICAL_REBOUND, "reward": RewardType.ENERGY_SURGE, "title": "Corner Rebound Detonation", "desc": "Rebound from corner slingshot 3 times.", "activation_req": "Rebound from slingshot 3 times.", "reward_desc": "+75 Energy Surge to ball", "energy": 75, "required_widget": CellType.SLINGSHOT, "threshold": 3})
	_def(&"detonation_triangle_twin", "Dual Slingshot Pincer", 2, "3x3 V-Pincer", "Dual Angled Slingshot Kickers. Alternating deflections charge both wedges, detonating in an explosive shockwave (+85 energy).", [Vector2i(0,0), Vector2i(2,0), Vector2i(0,1), Vector2i(1,1), Vector2i(2,1), Vector2i(1,2)], {Vector2i(0,0): CellType.SLINGSHOT, Vector2i(2,0): CellType.SLINGSHOT, Vector2i(1,2): CellType.BUMPER}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.TACTICAL_REBOUND, "reward": RewardType.ENERGY_SURGE, "title": "Pincer Shockwave", "desc": "Charge pincer slingshots.", "activation_req": "Deflect off pincers 4 times.", "reward_desc": "+85 Energy Surge to ball", "energy": 85, "required_widget": CellType.SLINGSHOT, "threshold": 4})
	# T3
	_def(&"detonation_triangle_bastion", "Storm Slingshot Bastion", 3, "4x3 Fortress Wedge", "Heavy Triangular Slingshot Bastion. Absorbs 5 hits while crawling with intense lightning arcs, detonating in a massive board blast (+130 energy).", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(3,0), Vector2i(0,1), Vector2i(1,1), Vector2i(2,1), Vector2i(0,2), Vector2i(1,2)], {Vector2i(1,0): CellType.SLINGSHOT, Vector2i(2,1): CellType.SLINGSHOT, Vector2i(0,2): CellType.POP_BUMPER}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.TACTICAL_REBOUND, "reward": RewardType.ENERGY_SURGE, "title": "Storm Bastion Cataclysm", "desc": "Charge storm slingshot bastion.", "activation_req": "Deflect off bastion 5 times.", "reward_desc": "+130 Energy Surge + Board Blast", "energy": 130, "required_widget": CellType.SLINGSHOT, "threshold": 5})
	_def(&"detonation_triangle_apex", "Apex Overcharge Wedge", 3, "4x3 Diagonal Rampart", "Apex Overcharge Slingshot Wedge. Deflects incoming volleys with immense velocity; 5 hits triggers Global Board Knock.", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(0,1), Vector2i(1,1), Vector2i(0,2), Vector2i(3,0), Vector2i(2,1), Vector2i(1,2)], {Vector2i(2,0): CellType.SLINGSHOT, Vector2i(0,2): CellType.SLINGSHOT, Vector2i(1,1): CellType.POP_BUMPER}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.TACTICAL_REBOUND, "reward": RewardType.GLOBAL_BOARD_KNOCK, "title": "Apex Slingshot Knock", "desc": "Overcharge apex slingshot wedge.", "activation_req": "Deflect off wedge 5 times.", "reward_desc": "Global Board Knock (All pegs hit once)", "required_widget": CellType.SLINGSHOT, "threshold": 5})

static func _build_bash_toys() -> void:
	# T1
	_def(&"bash_toy_idol", "Lesser Goblin Idol", 1, "2x2 Square Totem", "Compact 4-Peg Bash Toy Setpiece. Absorbs 4 hits before crumbling, awarding +45 energy surge.", [Vector2i(0,0), Vector2i(1,0), Vector2i(0,1), Vector2i(1,1)], {}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.UNIFIED, CellType.BASH_TOY, {"type": GoalArchetype.BASH_DEMOLITION, "reward": RewardType.ENERGY_SURGE, "title": "Idol Demolition", "desc": "Shatter goblin idol.", "activation_req": "Strike idol 4 times.", "reward_desc": "+45 Energy Surge to ball", "energy": 45, "required_widget": CellType.BASH_TOY, "threshold": 4})
	_def(&"bash_toy_anvil", "Blacksmith Anvil", 1, "3x2 Heavy Block", "Rectangular Anvil Bash Toy. Sturdy centerpiece absorbing 4 heavy impacts to shatter with +50 energy.", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(0,1), Vector2i(1,1), Vector2i(2,1)], {Vector2i(1,0): CellType.BASH_TOY, Vector2i(0,0): CellType.BUMPER, Vector2i(2,0): CellType.BUMPER}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.BASH_DEMOLITION, "reward": RewardType.ENERGY_SURGE, "title": "Anvil Quench", "desc": "Strike blacksmith anvil.", "activation_req": "Strike anvil 4 times.", "reward_desc": "+50 Energy Surge to ball", "energy": 50, "required_widget": CellType.BASH_TOY, "threshold": 4})
	# T2
	_def(&"golem_effigy", "Golem Effigy", 2, "2x2 Boss Statue", "Unified 4-Peg Heavy Bash Toy (5 Hits). Stone effigy setpiece absorbing repeated impacts before shattering all board pegs.", [Vector2i(0,0), Vector2i(1,0), Vector2i(0,1), Vector2i(1,1)], {}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.UNIFIED, CellType.BASH_TOY, {"type": GoalArchetype.BASH_DEMOLITION, "reward": RewardType.GLOBAL_BOARD_KNOCK, "title": "Golem Demolition", "desc": "Shatter the golem effigy.", "activation_req": "Strike golem effigy 5 times.", "reward_desc": "Global Board Knock (All pegs hit once)", "required_widget": CellType.BASH_TOY, "threshold": 5})
	_def(&"bash_toy_bell", "Gilded Temple Bell", 2, "3x3 Stepped Bell", "Temple Bell Bash Toy Setpiece. Absorbs 6 hits to resonate across the board with +85 energy surge.", [Vector2i(1,0), Vector2i(0,1), Vector2i(1,1), Vector2i(2,1), Vector2i(0,2), Vector2i(1,2), Vector2i(2,2)], {Vector2i(1,1): CellType.BASH_TOY, Vector2i(0,1): CellType.BUMPER, Vector2i(2,1): CellType.BUMPER}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.BASH_DEMOLITION, "reward": RewardType.ENERGY_SURGE, "title": "Temple Bell Chime", "desc": "Resonate temple bell.", "activation_req": "Strike temple bell 6 times.", "reward_desc": "+85 Energy Surge to ball", "energy": 85, "required_widget": CellType.BASH_TOY, "threshold": 6})
	# T3
	_def(&"blood_tithe", "Colossus War Effigy", 3, "4x3 Horseshoe Arch", "Massive War Effigy Setpiece with 3 surrounding pop bumpers. Takes 8 heavy strikes to shatter with +150 Energy.", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(3,0), Vector2i(0,1), Vector2i(3,1), Vector2i(0,2), Vector2i(1,2), Vector2i(2,2), Vector2i(3,2)], {Vector2i(1,0): CellType.BASH_TOY, Vector2i(0,0): CellType.POP_BUMPER, Vector2i(3,0): CellType.POP_BUMPER, Vector2i(0,2): CellType.POP_BUMPER}, {Vector2i(1,0): Vector2i.DOWN}, EnclosureType.DIRECTIONAL_FUNNEL, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.BASH_DEMOLITION, "reward": RewardType.ENERGY_SURGE, "title": "Colossus Shatter", "desc": "Demolish colossus war effigy.", "activation_req": "Strike war effigy 8 times.", "reward_desc": "+150 Energy Surge to ball", "energy": 150, "required_widget": CellType.BASH_TOY, "threshold": 8})
	_def(&"gilded_covenant", "Dragon Treasure Chest", 3, "4x3 Vault Chamber", "Giant Vault Bash Toy Setpiece. Takes 8 hits to burst open, unleashing a 3-ball Multiball Cascade and board shockwave.", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(3,0), Vector2i(0,1), Vector2i(1,1), Vector2i(3,1), Vector2i(0,2), Vector2i(1,2), Vector2i(2,2), Vector2i(3,2)], {Vector2i(2,2): CellType.BASH_TOY, Vector2i(0,0): CellType.BUMPER, Vector2i(3,0): CellType.BUMPER}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.BASH_DEMOLITION, "reward": RewardType.MULTIBALL_CASCADE, "title": "Dragon Chest Breach", "desc": "Smash open dragon treasure chest.", "activation_req": "Strike treasure chest 8 times.", "reward_desc": "Multiball Cascade (3 balls)", "balls": 3, "required_widget": CellType.BASH_TOY, "threshold": 8})

static func _build_spinners() -> void:
	# T1
	_def(&"funneled_spinner_chute", "Funneled Chute Spinner", 1, "2x3 Vertical Chute", "Vertical Chute Spinner. Funnel rails guide balls straight into spinner blades; 6 revs triggers +35 energy and cooldown.", [Vector2i(0,0), Vector2i(1,0), Vector2i(0,1), Vector2i(1,1), Vector2i(0,2)], {Vector2i(0,1): CellType.SPINNER}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SPINNER_RPM, "reward": RewardType.ENERGY_SURGE, "title": "Chute Spinner Surge", "desc": "Rev chute spinner.", "activation_req": "Rev spinner 6 revolutions.", "reward_desc": "+35 Energy Surge to ball", "energy": 35, "required_widget": CellType.SPINNER, "threshold": 6})
	_def(&"funneled_spinner_v", "V-Funnel Pocket Spinner", 1, "3x2 V-Funnel", "Angled Guide Rails funnel balls into pocket spinner; 6 revs triggers +40 energy and cooldown.", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(1,1), Vector2i(2,1)], {Vector2i(1,0): CellType.SPINNER, Vector2i(0,0): CellType.GUIDE_RAIL, Vector2i(2,0): CellType.GUIDE_RAIL}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SPINNER_RPM, "reward": RewardType.ENERGY_SURGE, "title": "Pocket Spinner Rev", "desc": "Rev pocket spinner.", "activation_req": "Rev spinner 6 revolutions.", "reward_desc": "+40 Energy Surge to ball", "energy": 40, "required_widget": CellType.SPINNER, "threshold": 6})
	# T2
	_def(&"funneled_spinner", "Funneled Kinetic Spinner", 2, "3x3 Funnel Frame", "Funnel Deflection Walls channel balls directly into central spinner. 8 revolutions triggers +80 Energy Surge and cooldown.", [Vector2i(0,0), Vector2i(2,0), Vector2i(0,1), Vector2i(1,1), Vector2i(2,1), Vector2i(1,2)], {Vector2i(1,1): CellType.SPINNER, Vector2i(0,0): CellType.GUIDE_RAIL, Vector2i(2,0): CellType.GUIDE_RAIL}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SPINNER_RPM, "reward": RewardType.ENERGY_SURGE, "title": "Funneled RPM Burst", "desc": "Rev kinetic spinner.", "activation_req": "Rev spinner 8 revolutions.", "reward_desc": "+80 Energy Surge to ball", "energy": 80, "required_widget": CellType.SPINNER, "threshold": 8})
	_def(&"funneled_spinner_dual", "Dual Funnel Rev Engine", 2, "3x3 U-Chamber", "Dual Funneled Spinners flanked by deflection walls. 8 revolutions triggers +90 Energy Surge and cooldown.", [Vector2i(0,0), Vector2i(2,0), Vector2i(0,1), Vector2i(1,1), Vector2i(2,1), Vector2i(0,2), Vector2i(2,2)], {Vector2i(0,1): CellType.SPINNER, Vector2i(2,1): CellType.SPINNER, Vector2i(1,1): CellType.BUMPER}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SPINNER_RPM, "reward": RewardType.ENERGY_SURGE, "title": "Dual Rev Surge", "desc": "Rev dual spinners.", "activation_req": "Rev dual spinners 8 revolutions.", "reward_desc": "+90 Energy Surge to ball", "energy": 90, "required_widget": CellType.SPINNER, "threshold": 8})
	# T3
	_def(&"resonant_well", "Resonant Well", 3, "4x3 Resonator Ring", "Dual Spinners + Dual Pop Bumpers in a resonant resonator frame. 10 revolutions triggers +140 energy surge.", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(3,0), Vector2i(0,1), Vector2i(1,1), Vector2i(2,1), Vector2i(3,1), Vector2i(0,2), Vector2i(1,2), Vector2i(2,2), Vector2i(3,2)], {Vector2i(1,0): CellType.SPINNER, Vector2i(2,2): CellType.SPINNER, Vector2i(0,1): CellType.POP_BUMPER, Vector2i(3,1): CellType.POP_BUMPER}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SPINNER_RPM, "reward": RewardType.ENERGY_SURGE, "title": "Resonant Spinner Surge", "desc": "Rev dual spinners.", "activation_req": "Rev dual spinners 10 revolutions.", "reward_desc": "+140 Energy Surge to ball", "energy": 140, "required_widget": CellType.SPINNER, "threshold": 10})
	_def(&"funneled_spinner_vortex", "Overdrive Vortex Spinner", 3, "4x3 Vortex Chamber", "Dual Funneled Spinners in an enclosed vortex frame. 10 revs triggers Global Board Knock and supercharges all board pegs.", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(3,0), Vector2i(0,1), Vector2i(3,1), Vector2i(0,2), Vector2i(1,2), Vector2i(2,2), Vector2i(3,2)], {Vector2i(1,0): CellType.SPINNER, Vector2i(2,2): CellType.SPINNER, Vector2i(0,0): CellType.POP_BUMPER, Vector2i(3,0): CellType.POP_BUMPER}, {}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SPINNER_RPM, "reward": RewardType.GLOBAL_BOARD_KNOCK, "title": "Vortex Spinner Knock", "desc": "Rev vortex spinners to max RPM.", "activation_req": "Rev vortex spinners 10 revolutions.", "reward_desc": "Global Board Knock (All pegs hit once)", "required_widget": CellType.SPINNER, "threshold": 10})

static func _build_momentum_tracks() -> void:
	# T1
	_def(&"track_stairs_step", "Staircase Speed Rail", 1, "Z-Step Polyomino", "Stepped Stair Polyomino. Downward speed wheels boost ball velocity through a 2-stage stepped descent (+35 energy).", [Vector2i(0,0), Vector2i(0,1), Vector2i(1,1), Vector2i(1,2)], {Vector2i(0,0): CellType.ACCELERATOR, Vector2i(1,2): CellType.ACCELERATOR}, {Vector2i(0,0): Vector2i.RIGHT, Vector2i(1,2): Vector2i.DOWN}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SEQUENCE_ROUTE, "reward": RewardType.ENERGY_SURGE, "title": "Staircase Flow", "desc": "Traverse staircase rail.", "activation_req": "Traverse staircase speed rail.", "reward_desc": "+35 Energy Surge to ball", "energy": 35, "required_widget": CellType.ACCELERATOR, "threshold": 1})
	_def(&"track_right_angle", "Right-Angle Elbow Chute", 1, "L-Turn Polyomino", "L-Turn Polyomino. Speed wheel accelerates ball into a sharp 90-degree right angle turn to redirect board flow (+40 energy).", [Vector2i(0,0), Vector2i(0,1), Vector2i(0,2), Vector2i(1,2)], {Vector2i(0,0): CellType.ACCELERATOR, Vector2i(0,2): CellType.GUIDE_TRACK, Vector2i(1,2): CellType.ACCELERATOR}, {Vector2i(0,0): Vector2i.DOWN, Vector2i(1,2): Vector2i.RIGHT}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SEQUENCE_ROUTE, "reward": RewardType.ENERGY_SURGE, "title": "Elbow Turn Flow", "desc": "Traverse right-angle turn.", "activation_req": "Traverse right-angle elbow chute.", "reward_desc": "+40 Energy Surge to ball", "energy": 40, "required_widget": CellType.ACCELERATOR, "threshold": 1})
	# T2
	_def(&"track_u_turn", "U-Turn Momentum Loop", 2, "U-Turn Polyomino", "U-Shape Polyomino. 180-degree turnaround track with dual accelerators launches balls back up into playfield combos (+75 energy).", [Vector2i(0,0), Vector2i(0,1), Vector2i(1,1), Vector2i(2,1), Vector2i(2,0)], {Vector2i(0,0): CellType.ACCELERATOR, Vector2i(1,1): CellType.GUIDE_TRACK, Vector2i(2,0): CellType.ACCELERATOR}, {Vector2i(0,0): Vector2i.DOWN, Vector2i(2,0): Vector2i.UP}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.ORBIT_FLOW, "reward": RewardType.ENERGY_SURGE, "title": "U-Turn Momentum Surge", "desc": "Complete U-turn turnaround.", "activation_req": "Traverse U-turn loop.", "reward_desc": "+75 Energy Surge to ball", "energy": 75, "required_widget": CellType.ORBIT_LOOP, "threshold": 1})
	_def(&"track_zigzag_chute", "Zigzag Switchback Track", 2, "S-Curve Snake Polyomino", "Snake/Slalom Polyomino. Alternating speed wheels drive high-velocity zigzag flow across playfield lanes (+80 energy).", [Vector2i(0,0), Vector2i(1,0), Vector2i(1,1), Vector2i(2,1), Vector2i(2,2)], {Vector2i(0,0): CellType.ACCELERATOR, Vector2i(1,1): CellType.GUIDE_TRACK, Vector2i(2,2): CellType.ACCELERATOR}, {Vector2i(0,0): Vector2i.DOWN, Vector2i(2,2): Vector2i.DOWN}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SEQUENCE_ROUTE, "reward": RewardType.ENERGY_SURGE, "title": "Zigzag Slalom Flow", "desc": "Traverse zigzag switchback.", "activation_req": "Traverse zigzag switchback track.", "reward_desc": "+80 Energy Surge to ball", "energy": 80, "required_widget": CellType.ACCELERATOR, "threshold": 1})
	# T3
	_def(&"track_grand_orbit", "Grand Orbit Loop Track", 3, "Closed Loop Polyomino", "Closed Loop Polyomino with open center. 4 corner accelerators maintain continuous high-speed orbital loop (+140 energy).", [Vector2i(0,0), Vector2i(1,0), Vector2i(2,0), Vector2i(3,0), Vector2i(0,1), Vector2i(3,1), Vector2i(0,2), Vector2i(1,2), Vector2i(2,2), Vector2i(3,2)], {Vector2i(0,0): CellType.ACCELERATOR, Vector2i(3,0): CellType.ACCELERATOR, Vector2i(3,2): CellType.ACCELERATOR, Vector2i(0,2): CellType.ACCELERATOR}, {Vector2i(0,0): Vector2i.RIGHT, Vector2i(3,0): Vector2i.DOWN, Vector2i(3,2): Vector2i.LEFT, Vector2i(0,2): Vector2i.UP}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.ORBIT_FLOW, "reward": RewardType.ENERGY_SURGE, "title": "Grand Orbit Continuous Loop", "desc": "Traverse closed orbit loop.", "activation_req": "Complete grand orbit loop.", "reward_desc": "+140 Energy Surge to ball", "energy": 140, "required_widget": CellType.ORBIT_LOOP, "threshold": 1})
	_def(&"track_cascade_switchback", "Grand Switchback Pipeline", 3, "Grand Stair-and-Loop Polyomino", "Multi-Stage Stair and Loop Polyomino. Accelerators feed falling balls through deep switchbacks, launching a 3-ball cascade (+150 energy).", [Vector2i(0,0), Vector2i(1,0), Vector2i(1,1), Vector2i(2,1), Vector2i(2,2), Vector2i(3,2), Vector2i(3,1), Vector2i(3,0)], {Vector2i(0,0): CellType.ACCELERATOR, Vector2i(2,1): CellType.ACCELERATOR, Vector2i(3,0): CellType.ACCELERATOR}, {Vector2i(0,0): Vector2i.DOWN, Vector2i(2,1): Vector2i.RIGHT, Vector2i(3,0): Vector2i.UP}, EnclosureType.OPEN_FRAME, {}, MachineryLayoutMode.PER_CELL, CellType.EMPTY, {"type": GoalArchetype.SEQUENCE_ROUTE, "reward": RewardType.MULTIBALL_CASCADE, "title": "Grand Switchback Volley", "desc": "Traverse switchback pipeline.", "activation_req": "Traverse grand switchback pipeline.", "reward_desc": "Multiball Cascade (3 balls) + 150 Energy", "energy": 150, "balls": 3, "required_widget": CellType.ACCELERATOR, "threshold": 1})
