@tool
extends RefCounted
## Resolves relic names and old completion-title references.

## String relic ID -> display name.
const NAMES: Dictionary = {
	"bumper_vessel_twin": "Bouncy Bumpers",
	"bumper_vessel_stagger": "Charged Bumpers",
	"pachinko_bumper_vessel": "Springy Bumpers",
	"bumper_vessel_pinball": "Splintering Bumpers",
	"mega_pop_bumper": "Thundering Bumper",
	"cyclone_bounce_vault": "Irrepressible Bumpers",
	"word_bank_gob": "Charged Letters",
	"word_bank_pop": "Iron Letters",
	"word_bank_win": "Crackling Letters",
	"word_bank_bam": "Explosive Letters",
	"word_bank_boom": "Cataclysmic Letters",
	"word_bank_loot": "Swarming Letters",
	"wire_gate_cup": "Charged Cup",
	"wire_gate_funnel": "Iron Funnel",
	"wire_gate_reservoir": "Teeming Reservoir",
	"abyssal_maw": "Splintering Well",
	"wire_gate_armory": "Cataclysmic Vault",
	"fragment_swarm": "Shattering Reservoir",
	"detonation_triangle_wedge": "Splitting Wedge",
	"detonation_triangle_acute": "Bouncy Slingshot",
	"corner_slingshot": "Surging Slingshot",
	"detonation_triangle_twin": "Explosive Slingshot",
	"detonation_triangle_bastion": "Cataclysmic Slingshot",
	"detonation_triangle_apex": "Irrepressible Slingshot",
	"bash_toy_idol": "Bouncy Idol",
	"bash_toy_anvil": "Splitting Anvil",
	"bash_toy_bell": "Surging Bell",
	"golem_effigy": "Explosive Effigy",
	"blood_tithe": "Binary Effigy",
	"gilded_covenant": "Swarming Chest",
	"funneled_spinner_chute": "Splitting Spinner",
	"funneled_spinner_v": "Charged Spinner",
	"funneled_spinner": "Splintering Spinner",
	"funneled_spinner_dual": "Teeming Spinner",
	"resonant_well": "Thundering Spinner",
	"funneled_spinner_vortex": "Irrepressible Spinner",
	"track_stairs_step": "Charged Stairs",
	"track_right_angle": "Splitting Elbow",
	"track_u_turn": "Springy Loop",
	"track_zigzag_chute": "Surging Switchback",
	"track_grand_orbit": "Shattering Orbit",
	"track_cascade_switchback": "Swarming Switchback",
	"cascade_reactor": "Scrap Bumpers",
	"perpetual_engine": "Endless Rail",
	"storm_of_fragments": "Jagged Bumpers",
	"explosive_contagion": "Sooty Slingshots",
	"superconductor": "Copper Target",
	"rubber_storm": "Padded Bumpers",
	"overdrive_cascade": "Winding Rail",
	"goblin_width_tempest": "Goblin Kicker",
	"crown_ricochet": "Crowned Bumpers",
	"twin_mandate": "Forked Rail",
	"velocity_dividend": "Dented Vault",
	"phase_sovereign": "Crooked Diverter",
	"renewal_pact": "Patched Slingshots",
	"iron_bloom": "Iron Targets",
	"echoes_of_wrench": "Wrench Targets",
	"stormgrid_coupling": "Copper Effigy",
	"leech_singularity": "Leech Knocker",
	"phantom_resonance": "Ghostly Rail",
	"supernova_peg": "Scorched Targets",
	"chain_conduction": "Copper Bumpers",
	"overcharged_drain": "Copper Reservoir",
	"final_arc_detonation": "Copper Kicker",
	"energy_collapse": "Sunken Targets",
	"shrapnel_split": "Jagged Diverter",
	"energized_fragments": "Copper Spinner",
	"arc_twins": "Paired Rail",
	"phase_siphon": "Faded Letters",
	"phase_detonation": "Scorched Rail",
	"spectral_conduit": "Spectral Rail",
	"impact_burst": "Dented Bumpers",
	"kinetic_charge": "Clockwork Spinner",
	"static_bounce": "Copper Letters",
	"parasitic_arc": "Leech Diverter",
	"draining_fragments": "Leech Slingshot",
	"resonant_bounce": "Ringing Targets",
	"ricochet_blast": "Dented Targets",
	"blast_launch": "Sooty Kicker",
	"arc_surge_wrench": "Wrench Slingshot",
	"goblin_width_pulse": "Goblin Sinkhole",
	"magnet_arc_snare": "Magnetic Lock",
	"spark_trampoline": "Copper Knocker",
	"hyper_elastic": "Coiled Rail",
	"overdrive_hits": "Clockwork Bumper",
	"overclock_network": "Clockwork Rail",
	"spreading_rot": "Rotten Target",
	"cluster_grenade": "Sooty Bumpers",
	"blast_lift": "Scorched Kicker",
	"fragmentation_tag": "Jagged Bumper",
	"storm_feedback": "Copper Slingshot",
	"overcurrent_surge": "Tarnished Letters",
	"fragment_echo": "Jagged Sinkhole",
	"mass_cascade": "Heavy Knocker",
	"ghost_trail": "Haunted Rail",
	"phase_instability": "Warped Rail",
	"chest_random_ball": "Stolen Knocker",
	"plain_surge": "Scrap Diverter",
	"plain_horde": "Scrap Bumper",
	"plain_momentum": "Scrap Rail",
	"volt_primer": "Etched Letters",
	"explosion_radius": "Sooty Slingshot",
	"explosion_peg_hit_count": "Sooty Lock",
	"explosion_impulse": "Dented Kicker",
	"chain_arc": "Linked Rail",
	"chain_range": "Copper Rail",
	"max_energize_stacks": "Tarnished Reservoir",
	"energize_decays_slower": "Tarnished Rail",
	"energized_pegs_repair_faster": "Patched Rail",
	"global_peg_durability": "Armored Bumpers",
	"peg_recovery_speed": "Clockwork Slingshots",
	"devastating_barrage": "Sooty Letters",
	"compressed_charge": "Dented Locks",
	"chest_leech_drain": "Rusty Slingshot",
	"chest_leech_duration": "Leech Rail",
	"chest_phantom_energy": "Pale Rail",
	"chest_rubbery_energy": "Coiled Spinner",
	"chest_bounce_energy": "Dented Bumper",
	"chest_split_energy": "Rusty Diverter",
	"apex_orbit_loop": "Crested Orbit",
	"cyclone_orbit_loop": "Spiraling Orbit",
	"grand_orbit_circuit": "Grand Orbit",
}

## Returns a resolved name based on the given ID, with a fallback option.
static func resolve(id: StringName, fallback: String) -> String:
	var key: String = str(id)
	if key == "chain_surge_wrench":
		key = "arc_surge_wrench"
	if NAMES.has(key):
		return str(NAMES[key])
	if fallback.begins_with("Fused Module Tier ") and fallback.trim_prefix("Fused Module Tier ").is_valid_int():
		return "Fused Device"
	return fallback

## Updates only known old goal titles.
static func resolve_goal_title(id: StringName, title: String) -> String:
	var old_names: Dictionary = {"crown_ricochet": "Crown Ricochet", "ghost_trail": "Ghost Trail", "word_bank_bam": "B-A-M Word Bank", "funneled_spinner_dual": "Pulse Spinner"} ## ID -> old title.
	if old_names.has(str(id)) and old_names[str(id)] == title:
		return resolve(id, title)
	return title
